name: Push

on:
  workflow_dispatch:

jobs:
  push:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout base
      uses: actions/checkout@v4
    - name: Create-github-token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ SECRETS.AUTHENTICATION_APP_ID }}
        private-key: ${{ SECRETS.AUTHENTICATION_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
    - name: Run sltt
      uses: ./.github/actions/sltt
      with:
        projects_dir: '.'
        sltt_arguments: "--mode push"
        email_address: ${{ vars.EMAIL_ADDRESS }}
        github_token: ${{ steps.app-token.outputs.token }}
        base_commit_sha: ${{ github.sha }}
